pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

rootProject.name = 'simpleportals'

includeBuild("libs/simplemodslib") {
    dependencySubstitution {
        substitute module("net.zarathul:simplemodslib") using project(":")
    }
}